site_name: Imbi Automations CLI
site_description: CLI framework for executing dynamic workflows across software project repositories with deep integration to the Imbi project management system.
site_author: Gavin M. Roy
site_url: https://imbi-automations.readthedocs.io/

repo_name: imbi/imbi-automations-cli
repo_url: https://github.com/imbi/imbi-automations-cli

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Basic Usage: getting-started/usage.md
  - User Guide:
    - Workflows: user-guide/workflows.md
    - Actions: user-guide/actions.md
    - Templates: user-guide/templates.md
    - Conditions: user-guide/conditions.md
  - API Reference:
    - CLI Commands: api/cli.md
    - Clients: api/clients.md
    - Models: api/models.md
  - Development:
    - Contributing: development/contributing.md
    - Architecture: development/architecture.md
    - Testing: development/testing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
